# Default values for StreamSets Transformer
image:
  repository: streamsets/transformer
  tag: latest
  pullPolicy: Always

rbac:
  enabled: true

controlHub:
  enabled: false
  url: https://cloud.streamsets.com
  ## Transformer auth token from the Control Hub REST API or UI
  token: ""
  ## Labels for this Transformer to report the Control Hub
  labels: all

transformer:
  ## External URL for Transformer, value for configuration "transformer.base.http.url" in transformer.properties
  baseHttpUrl: ""
  ## Java truststore file & password which stores certificates to trust identity of transformer launcher
  truststoreFile: ""
  truststorePassword: "password"
  env: {}

ingress:
  enabled: false
  path: "/"
  proto: https
  # Used to create an Ingress record.
  domain: ""
  host: ""
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: \"false\"
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/ingress.allow-http: "true"
    # kubernetes.io/ingress.class: traefik

persistence:
  ## Persistent Volume is required for Cluster Deployment Mode Support in Kubernetes Spark Cluster Manager type
  ## To share pipeline.json, offset.json and resources from Transformer launcher pod to driver pod.
  enabled: true
  annotations: {}
  ## Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is set,
  ##   choosing the default provisioner.  (gp2 on AWS, standard on GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 1Gi

route:
  ## For OpenShift/MiniShift
  enabled: false

resources: {}

nodeSelector: {}
